name       : graalvm
version    : 22.0.0.2
release    : 2
source     :
    - git|https://github.com/oracle/graal.git : vm-ce-22.0.0.2
    - git|https://github.com/graalvm/mx.git : 5.317.4
    - https://github.com/graalvm/labs-openjdk-11/releases/download/jvmci-22.0-b02/labsjdk-ce-11.0.13+8-jvmci-22.0-b02-linux-amd64.tar.gz : fc7a9507f720b162fdf3a3fcd20fb9e5200391a52642492ce996e4923d195105
license    : GPL-2.0-or-later
component  : programming.tools
networking : yes
clang      : yes
summary    : High Performan—Åe. Cloud Native. Polyglot.
description: |
    GraalVM is an ecosystem for compiling and running applications written in most modern programming languages and offers the following benefits:
builddeps    :
    - glibc-devel
build      : |
    unset CFLAGS
    unset LDFLAGS

    # Setup the custom jdk required to build graal
    # we need a special version of java to build which includes some needed headers
    cp $sources/labsjdk-ce-11.0.13+8-jvmci-22.0-b02-linux-amd64.tar.gz $workdir
    tar xvf labsjdk-ce-11.0.13+8-jvmci-22.0-b02-linux-amd64.tar.gz
    export JAVA_HOME=$workdir/labsjdk-ce-11.0.13-jvmci-22.0-b02/

    # Setup MX build tool
    mkdir -p $workdir/mx-build-tool
    cp -r $sources/mx.git $workdir
    export PATH=$workdir/mx.git:$PATH

    # Finally Build Graal
    cd $workdir/vm
    mx --env ce build

    cd $workdir/substratevm
    mx graalvm-show
    mx build
    mx graalvm-home
install    : |
    install -dm00755 $installdir/usr/share/graalvm
    cp -r $workdir/sdk/latest_graalvm_home/* -t $installdir/usr/share/graalvm/

    # empty folder if it exists creates a devel eopkg package
    rm -Rf $installdir/usr/include/graalvm
    chown -R root:root $installdir/usr/share/graalvm/
